// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qlcjjmtjocsauszbkyrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsY2pqbXRqb2NzYXVzemJreXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NjM2MjAsImV4cCI6MjA4MzEzOTYyMH0.4y3vLEhYBR1B64znN4pcqswub8WPR74C8d-jErlw1X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);